controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
    
clientes_index:
    path: /Clientes/
    controller: App\Controller\ClientesController::index
    methods: GET

app_exportar_clientes_pdf:
    path: /clientes/exportar-pdf
    controller: App\Controller\ClientesController::exportarAPdf
    methods: GET